version: '3.1'

services:
  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: hogehoge
    volumes:
      - ./redmine/plugins:/usr/src/redmine/plugins

  db:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: redmine
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/data:/var/lib/mysql
